### ISSUE TITLE
what is this iam doing something wrong ??

### ISSUE THREAD

**Issue by beaste69** [clipssender31/Snapchat-Account-Creator#6]
![image](https://user-images.githubusercontent.com/98755775/179209456-f5827f04-9fc8-4d0d-8a10-0c7c8797c95b.png)

**Comment by louisgaming** [comment]
you simple have invalid proxies.
I reccommend using these: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt

Work 75% of time.

Also set threads to higher for faster creation

**Comment by beaste69** [comment]
is it working ??


![image](https://user-images.githubusercontent.com/98755775/179211415-f57800b7-3d73-4014-bb79-fe00d0574bb8.png)

**Comment by beaste69** [comment]
> you simple have invalid proxies. I reccommend using these: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt
> 
> Work 75% of time.
> 
> Also set threads to higher for faster creation
> 
> Edit: I use 2000 threads

**Comment by beaste69** [comment]
@louisgaming
