### ISSUE TITLE
Captcha no longer solved

### ISSUE THREAD

**Issue by nathanoy** [clipssender31/Snapchat-Account-Creator#7]
No accounts were generating anymore. After investigation, i found that the message from the server always is:
`{"message": "Please solve the captcha."}` .

I can imagine that this is caused by an invalid anchor link. 
It could just as well be, that the captcha solver no longer works.

Could something be wrong with my setup?
I did a fresh clone of this repo, it yielded the same results.

**Comment by nathanoy** [comment]
after some research with the snap chat api, i found that my browser acually doesnt send a recaptcha response, it sends an `arkose-token`, which seems to be originated from `arkoselabs.com`. was that always present?

![cTVM4BYu0E](https://user-images.githubusercontent.com/89805394/179282783-01bb4803-136f-410a-b07f-6a15a1a2e2db.png)

**Comment by clipssender31** [comment]
Will further look into the issue.

**Comment by clipssender31** [comment]
I will not be updating this repo to fix the patch. Closing this issue...
